In [10]:
# Decision Tree 실습 - Weather 데이터에 적용하기

# 1. 데이터 준비
import pandas as pd
data = pd.read_csv('weather.csv', sep=',')

data

     outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
1   overcast        cool   normal   True  yes
2   overcast        mild     high   True  yes
3   overcast         hot   normal  False  yes
4      rainy        mild     high  False  yes
5      rainy        cool   normal  False  yes
6      rainy        cool   normal   True   no
7      rainy        mild   normal  False  yes
8      rainy        mild     high   True   no
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no
11     sunny        mild     high  False   no
12     sunny        cool   normal  False  yes
13     sunny        mild   normal   True  yes

In [11]:
# 2. 카테고리 문자열을 수치로 변환

# mapping dictionary 만들기
outlook_dic = {
               'overcast' : 0,
               'rainy' : 1,
               'sunny' : 2
               }
temperature_dic = {
                  'cool' : 0,
                  'hot' : 1,
                  'mild' : 2
                  }
humidity_dic = {
                'high' : 0,
                'normal' : 1
                }
windy_dic = { False : 0,
              True : 1 }

# dictionary 를 활용해 데이터 매핑
data['outlook'] = data['outlook'].map(outlook_dic)
data['temperature'] = data['temperature'].map(temperature_dic)
data['humidity'] = data['humidity'].map(humidity_dic)
data['windy'] = data['windy'].map(windy_dic)

data

    outlook  temperature  humidity  windy play
0         0            1         0      0  yes
1         0            0         1      1  yes
2         0            2         0      1  yes
3         0            1         1      0  yes
4         1            2         0      0  yes
5         1            0         1      0  yes
6         1            0         1      1   no
7         1            2         1      0  yes
8         1            2         0      1   no
9         2            1         0      0   no
10        2            1         0      1   no
11        2            2         0      0   no
12        2            0         1      0  yes
13        2            2         1      1  yes

In [15]:
# 3. 결정 트리 분류기 인스턴스 생성

# Decision Tree classifier instance 생성
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf

DecisionTreeClassifier()

In [17]:
# 4. 결정 트리 분류기 학습
a = clf.fit(data.iloc[:, :4], data['play'])

In [20]:
# 5. 오늘같은 날씨에는 필드에 나갈까? 예측하기

# 맑고, 온도가 적당하고, 습도가 높고, 바람이 분다
a = clf.predict([[2,2,0,1]])
print(a)

# 비가 오고, 온도가 적당하고, 습도가 높고, 바람이 분다
b = clf.predict([[1,2,0,1]])
print(b)

['no']
['no']

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"